#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/go/src/github.com/jddixon/gzog
  
  bl_listgen \
    -d ../gzog \
    -1L  \
    -u $DVCZ_UDIR \
    -X .ssh \
    $@
  
else
  echo "DEV_BASE is not defined"
fi
